# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/hodor.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hodor.HodorRequest" do
    optional :message, :string, 1
  end
  add_message "hodor.HodorResponse" do
    optional :message, :string, 1
  end
end

module Hodor
  HodorRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("hodor.HodorRequest").msgclass
  HodorResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("hodor.HodorResponse").msgclass
end
