# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/hodor.proto for package 'search'

require 'grpc'
require 'proto/hodor'

module Search
  module HodorService

    # TODO: add proto service documentation here
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'search.HodorService'

      rpc :talk, HodorRequest, HodorResponse
    end

    Stub = Service.rpc_stub_class
  end
end
